# Generated by Django 6.0.5 on 2026-05-30 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sede_id', models.BigIntegerField(null=True)),
                ('rol', models.CharField(max_length=10)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sede_id', models.BigIntegerField()),
                ('grado_id', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'grupos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estudiante_id', models.BigIntegerField()),
                ('asignatura_id', models.BigIntegerField()),
                ('periodo_id', models.BigIntegerField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fallas', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'notas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sedes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstudianteGrupo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='matriculas', to='core.estudiante')),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='matriculas', to='core.grupo')),
            ],
            options={
                'db_table': 'estudiante_grupo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='core.grupo'),
        ),
        migrations.CreateModel(
            name='UserActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fallas', models.IntegerField(default=0)),
                ('periodo', models.CharField(max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.grupo')),
            ],
            options={
                'verbose_name': 'Reporte Académico',
                'verbose_name_plural': 'Reportes Académicos',
                'db_table': 'reportes_academicos',
                'managed': True,
                'unique_together': {('grupo', 'estudiante', 'periodo')},
            },
        ),
    ]
