# Generated by Django 5.2.5 on 2025-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sede_id', models.BigIntegerField(null=True)),
                ('rol', models.CharField(max_length=10)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
